config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'


  authenticate :user do
    resources :lecturers do
      get :set_admin

    end
    resources :students do
      get :send_support
      get :send_attendance
    end
    resources :dashboard
    resources :classgroups
    resources :classsessions do
      get :review
      get :end_session
    end
    resources :quiz
    resource :enrollment
    resource :joinsession

  end

  get 'static_pages/index'
  devise_for :users, controllers: { registrations: "registrations", sign_in: "login" }
  root 'static_pages#index'

end

app/models/classsession.rb
class Classsession < ApplicationRecord
  belongs_to :classgroup, dependent: :destroy
  has_many :chatmessages, dependent: :destroy
  has_many :questionmessages, dependent: :destroy
  has_many :answermessages, dependent: :destroy
  has_many :chatmessages
  has_and_belongs_to_many :quizzes
  has_and_belongs_to_many :students
  has_many :understanding_polls
  validates :topic, presence: true
end

app/controllers/classsession_controller.rb
class ClasssessionController < ApplicationController

  def show
    @messages = Chatmessage.all
  end

end

app/controllers/classsessions_controller.rb
require 'json'
require 'date'
class ClasssessionsController < ApplicationController
  #SUPER AWESOME snippet of code suggestion from stack overflow to change the layout for a controller based on the action!
  #https://stackoverflow.com/questions/3025784/rails-layouts-per-action
  layout "session", only: [:show]

  def index
    redirect_to '/dashboard'
  end

  def show

    #Find the session we want to join
    @session = Classsession.find(params[:id])

    #Get all the Chat messages for the session
    @messages = @session.chatmessages

    #Get all the Questions asked for the session
    @questions = @session.questionmessages

    #Get all the answers given for a session
    @answers = @session.answermessages

    #Combine the Questions and Answers into one collection and sort it by the created at date.
    # This should hopefully retain correct order. The variable name is meant to read Q & A
    @qanda = (@questions + @answers).sort_by(&:created_at)

    #Get the current user logged in (Used for logic in the session)
    @user = current_user

    #Populate the graph with no data to begin with!
    @poll_data = {
        'Yes' => 0,
        'No' => 0
    }

    @quiz_data = {
        'Question One' => 0,
        'Question Two' => 0,
        'Question Three' => 0,
        'Question Four' => 0,
        'Question Five' => 0
    }

    #Get the Classgroup
    @classgroup = @session.classgroup

    #Get all the Quizzes associated with the Classgroup
    @quizzes = @classgroup.quizzes


    #This check is used to find out what the "User Type" is. This is either Lecturer or Student
    # I have abstracted the identifier into a random code just to make it more difficult for Students
    # To guess how to send messages as a Lecturer in the case of Malicious Activity

    if current_user.lecturer.nil?
      @user_type = get_student_code
      render 'student_show'
    else
      @user_type = get_lecturer_code
      render 'lecturer_show'
    end

  end

  def new
    @session = Classsession.new
    @classgroup = params[:classgroup]


  end

  def create

    #Manually Set all the Fields because some of the fields are set behind the scenes
    @session = Classsession.new
    @session.topic = classsession_params[:topic]
    @session.start_time = DateTime.now
    @session.end_time = classsession_params[:end_time]
    @session.is_active = true
    @session.extra_help = classsession_params[:extra_help]
    @classgroup_id = classsession_params[:classgroup_id]
    @classgroup = Classgroup.find(@classgroup_id)
    @session.classgroup = @classgroup

    #Check if a Sessions already exists, if they do, make the new ID equal to the next available ID.
    # We do this because we need to generate the Session Key based on the ID of the Session, which is typically
    # Only generated when the Record is saved.
    if (Classsession.any?)
      @id = Classsession.maximum(:id).next
    else
      @id = 0
    end


    @session.id = @id
    @session.session_key = generate_key(@id)

    if @session.save
      redirect_to @session
    else
      render 'new'
    end
  end

  def destroy

  end

  def review

    #Get the Session to show the review for
    @session = Classsession.find(params[:classsession_id])

    #Get the Classgroup of the Session
    @classgroup = @session.classgroup

    #Get all the messages for the session
    @messages = @session.chatmessages
    #Get all the questions for the session
    @questions = @session.questionmessages
    #Get all the answers for the session
    @answers = @session.answermessages

    #Get Questions and Answers for the Session (This composes the Q&A History box)
    @qanda = (@questions + @answers).sort_by(&:created_at)

    render 'review'

  end

  def end_session
    @session = Classsession.find(params[:classsession_id])
    @session.is_active = false
    @session.end_time = DateTime.now

    @poll_count = @session.understanding_polls.count()


    #Check if the Lecturer Provided extra help materials
    if not @session.extra_help.nil?

      #If so, get all the students from the session
      @students = @session.students

      #Iterate over them
      @students.each do |stud|

        #Keep track of how much they understood
        @yes_count = 0


        #Get all their responses
        @understanding_responses = stud.understanding_responses

        #Iterate over the responses
        @understanding_responses.each do |resp|

          #Get the poll
          @temp_poll = resp.understanding_poll

          #Get the session associated with the poll
          @temp_session = @temp_poll.classsession

          #If the poll was assocaited with the ending session
          if @temp_session == @session

            #Check did they understand?
            if resp.understood
              #They did, so increment their yes counter
              @yes_count = @yes_count + 1
            end
          end
        end

        #Finally, check was their understanding under 50%
        if @yes_count < (@poll_count / 2)
          #Mail them the extra resources
          ClassistantMailer.with(student: stud, classsession: @session).help_email.deliver_now
        end
      end
    end

    @session.save

    redirect_to '/classsessions/' + @session.id.to_s + '/review'

  end

  private
  def classsession_params
    params.require(:classsession).permit(:topic, :end_time, :classgroup_id, :extra_help)
  end
end

app/helpers/classsession_helper.rb
module ClasssessionHelper
end

app/views/classsessions/_form.html.erb
<%= bootstrap_form_with(model: @session, local: true) do |form| %>
  <% if @session.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(@session.errors.count, "error") %> prohibited this Session from being saved:</h2>
      <ul>
        <% @session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= form.text_field :topic, label: "Topic of the Session"%>
    </div>
    <div class="field">
      <%= form.text_area :extra_help, label: "Additional resources to send to students who struggle during the Session (Text, YouTube link, etc)"%>
    </div>
    <div class="field">
      <%= form.hidden_field('classgroup_id', :value => @classgroup) %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit "Start Session", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/classsessions/_list.html.erb
<table class="table session-list-table">
  <thead>
  <tr>
    <th scope="col">Session Key</th>
    <th scope="col">Session Topic</th>
    <th scope="col">Session Start Time</th>
    <th scope="col">Session End Time</th>
    <th scope="col">Attendance</th>
    <th scope="col">Review</th>
    <th scope="col">Join</th>
  </tr>
  </thead>
  <tbody>
  <% @sessions.each do |session| %>
    <tr>
      <td><%= session.session_key %></td>
      <td><%= session.topic %></td>
      <td><%= session.start_time.strftime('%D - %H:%M') %></td>
      <% if not session.end_time.nil? %>
        <td><%= session.end_time.strftime('%D - %H:%M') %></td>
        <%else %>
      <td></td>
      <% end %>
      <td><%= session.students.count %></td>
      <td><%= link_to "Review", '/classsessions/' + session.id.to_s + '/review', class: 'btn btn-info' %></td>
      <% if session.is_active %>
        <td><%= link_to "Join", '/classsessions/' + session.id.to_s, class: 'btn btn-primary' %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/classsessions/_question_box.html.erb
<% @qanda.each do |msg| %>
  <% if msg.is_a? (Questionmessage)%>
    <% if msg.is_anon %>
      <p><span class="chat-timestamp"><%= msg.created_at.strftime('%H:%M') %></span> Anonymous: <%= msg.content %></p>
    <% else %>
      <p><span class="chat-timestamp"><%= msg.created_at.strftime('%H:%M') %></span> <%= msg.student.full_name %>: <%= msg.content %></p>
    <% end %>
  <% else %>
    <p class="lecturer-message"><span class="chat-timestamp"><%= msg.created_at.strftime('%H:%M') %></span> <span class="lecturer-name"><%= msg.lecturer.full_name %></span>: <%= msg.content %></p>
  <% end %>
<% end %>

app/views/classsessions/_question_box_lecturer.html.erb
<% @qanda.each do |msg| %>
  <% if msg.is_a? (Questionmessage)%>
    <div class="question-wrap">
      <% if msg.is_anon %>
        <p><span class="chat-timestamp"><%= msg.created_at.strftime('%H:%M') %></span> Anonymous: <%= msg.content %></p>
      <% else %>
        <p><span class="chat-timestamp"><%= msg.created_at.strftime('%H:%M') %></span> <%= msg.student.full_name %>: <%= msg.content %></p>
      <% end %>
      <p class="mid"><%= msg.id %></p>
      <button class="answer-btn">Answer Question</button>
    </div>
  <% else %>
    <p class="lecturer-message"><span class="chat-timestamp"><%= msg.created_at.strftime('%H:%M') %></span> <span class="lecturer-name"><%= msg.lecturer.full_name %></span>: <%= msg.content %></p>
  <% end %>

<% end %>

app/views/classsessions/_student_list.html.erb
<table class="table session-list-table">
  <thead>
  <tr>
    <th scope="col">Session Key</th>
    <th scope="col">Session Topic</th>
    <th scope="col">Session Start Time</th>
    <th scope="col">Session End Time</th>
    <th scope="col">Join / Review</th>
  </tr>
  </thead>
  <tbody>
  <% @sessions.each do |session| %>
    <tr>
      <td><%= session.session_key %></td>
      <td><%= session.topic %></td>
      <td><%= session.start_time %></td>

      <% if not session.end_time.nil? %>
        <td><%= session.end_time.strftime('%D - %H:%M') %></td>
      <%else %>
        <td></td>
      <% end %>
      <% if session.is_active %>
        <td><%= link_to "Join", '/classsessions/' + session.id.to_s, class: 'btn btn-primary ses-btn' %></td>
      <% else %>
        <td><%= link_to "Review", '/classsessions/' + session.id.to_s + '/review', class: 'btn btn-primary ses-btn' %></td>
      <% end %>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/classsessions/index.html.erb
<div class="row">
  <div class="col-md-12 classistant-body">
    <div class="heading">
      <h2>Join a Session</h2>
      <p>To join a Session simply enter the Session Code</p>
    </div>

    <div class="classistant-form centered-form">



    </div>
  </div>
</div>

app/views/classsessions/lecturer_show.html.erb
<div class="row classistant-body">
  <div class="col-md-12">
    <h1 class="heading">Welcome to your Classistant Session</h1>
    <h4 class="heading">Todays topic: <%= @session.topic %> (<%= @session.session_key %>)</h4>
  </div>
</div>
<div class="row classistant-body session-body">
  <div class="col-md-12" id="poll-response-pie">
    <h2 class="heading">Poll Results</h2>
    <button class="btn btn-danger poll-btn btn-block" id="end-poll" disabled>End Poll</button>
    <%= pie_chart @poll_data, id: "poll-responses" %>
  </div>
  <div class="col-md-12" id="quiz-response-graph">
    <h2 class="heading" id="quiz-heading">Quiz Results</h2>
    <button class="btn btn-danger poll-btn btn-block" id="end-quiz" disabled>End Quiz</button>
    <%= column_chart @quiz_data, id: "quiz-responses" %>
  </div>

</div>
<div class="row classistant-body session-body">
  <div class="col-md-6">
    <p class="chat-data" id="uid"><%= @user.id %></p>
    <p class="chat-data" id="utp"><%= @user_type %></p>
    <p class="chat-data" id="sid"><%= @session.id %></p>
    <h1 class="message-box-heading">Class Chat</h1>
    <div id="chat-messages" class="message-box">
      <%= render 'chatmessage/list' %>
    </div>
    <form class="chat-form">
      <input type="text" data-behavior="chat_send" class="message-field" id="chat-input" autocomplete="off" placeholder="Send a message..">
      <button class="btn btn-primary chat-btn" data-behavior="chat_send" id="send-chat">Send</button>
    </form>
  </div>
  <div class="col-md-6">
    <h1 class="message-box-heading">Class Questions</h1>
    <div id="question-messages" class="message-box">
      <%= render 'question_box_lecturer' %>
    </div>
    <form class="question-form">
      <input type="text" data-behavior="answer_send" class="message-field" id="answer-input" autocomplete="off" placeholder="Answer a Question..">
      <button class="btn btn-primary chat-btn" data-behavior="answer_send" id="answer-question">Send</button>
      <label for="answer-question" class="answer-label"></label>
      <p class="mid"></p>
    </form>
  </div>
</div>
<div class="row classistant-body session-body">
  <div class="col-md-12 interaction-actions">
    <h1 class="heading">Interact with your class</h1>
    <p class="heading">Below you will find a different ways to interact with your class</p>
    <div class="col-md-6 text-center interaction-box">
      <h3 class="heading">Polling</h3>
      <div class="col-md-12 text-center">
        <button class="btn btn-primary poll-btn btn-block" id="poll-class-understanding-text">Poll Understanding
          (Text)
        </button>
        <button class="btn btn-primary poll-btn btn-block" id="poll-class-understanding-image">Poll Understanding
          (Image)
        </button>
      </div>
    </div>
    <div class="col-md-6  interaction-box">
      <h3 class="heading">Quiz</h3>
      <div class="col-md-12">
        <%= render 'quiz/session_list' %>
      </div>
    </div>
  </div>
</div>
<div class="row classistant-body">
  <div class="col-md-12">
    <%= link_to("End Session", classsession_end_session_url(@session), class: "btn btn-danger btn-block") %>
  </div>
</div>

app/views/classsessions/new.html.erb
<div class="row classistant-body class-form-body">

  <div class="col-md-12 standard-form">

    <div class="classistant-form">

      <h2>Start a new Session</h2>
      <hr class="hr-dark">

      <%= render 'form'%>

    </div>
  </div>
</div>

<% link_to 'Back', dashboard_index_url%>

app/views/classsessions/review.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <h1 class="heading">Session Details</h1>
    </div>
  </div>
</div>

<div class="row classistant-body session-review-body">
  <div class="col-md-12">
    <h2 class="heading">Class Details</h2>
    <hr class="hr-dark">
    <%= render 'classgroups/student_heading' %>
  </div>
</div>
<div class="row classistant-body session-review-body">
  <div class="col-md-12">
    <h2 class="heading">Session Details</h2>
    <hr class="hr-dark">
    <div class="class-heading">
      <div class="class-details">
        <h2>Topic: <%= @session.topic %></h2>
        <div class="col-md-6">
          <p><strong>Session Key:</strong> <%= @session.session_key%></p>
          <p><strong>Additional Help:</strong> <%= @session.extra_help%></p>
          <p><strong>Attendance:</strong> <%= @session.students.count %></p>
          <p><strong>Questions Asked:</strong> <%= @questions.count %></p>
        </div>
        <div class="col-md-6">
          <p><strong>Messages Sent:</strong> <%= @messages.count %></p>
          <p><strong>Total Answers:</strong> <%= @answers.count %></p>
          <p><strong>Number of Polls:</strong> <%= @session.understanding_polls.count %></p>
          <p><strong>Number of Quizzes:</strong> <%= @session.quizzes.count %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row classistant-body session-review-body">
  <div class="col-md-12">
    <h2 class="heading">Questions and Answers Table</h2>
      <%= render 'questionmessage/question_answer_table' %>
  </div>
</div>
<div class="row classistant-body session-review-body">
  <div class="col-md-12">
    <h2 class="heading">Chat History</h2>
    <div class="chat-history">
      <%= render 'chatmessage/list' %>
    </div>
  </div>
</div>
<div class="row classistant-body session-review-body">
  <div class="col-md-12">
    <h2 class="heading">Questions and Answers History</h2>
    <div class="chat-history">
      <%= render 'questionmessage/history' %>
    </div>
  </div>
</div>

app/views/classsessions/show.html.erb
<div class="row classistant-body">
  <div class="col-md-12">
    <h1 class="heading">Welcome to your Classistant Session</h1>
    <h3><%= @session.topic %></h3>
    <p>Details might go here, shall see</p>
  </div>
</div>
<div class="row classistant-body">
  <div class="col-md-12">
    <h1>Interaction Box</h1>
    <p>Quizzes, Polls etc</p>
    <button class="btn primary poll-btn" id="poll-class-understanding">Poll Understanding</button>
  </div>
</div>
<div class="row classistant-body session-body">
  <div class="col-md-6">
    <p class="chat-data" id="uid"><%= @user.id %></p>
    <p class="chat-data" id="utp"><%= @user_type %></p>
    <p class="chat-data" id="sid"><%= @session.id %></p>
    <h1>Chat</h1>
    <div id="chat-messages" class="message-box">
      <%= render 'chatmessage/list'%>
    </div>
    <form class="chat-form">
      <input type="text" data-behavior="chat_send" class="message-field" id="chat-input" autocomplete="off">
      <button class="btn btn-primary chat-btn" data-behavior="chat_send" id="send-chat">Send</button>
      <br>
      <label class="anon-label"><input type="checkbox" name="checkbox" value="value" id="chat-anon-box">Send Message Anonymously</label>
    </form>
  </div>
  <div class="col-md-6">
    <h1>Ask a Question</h1>
    <div id="question-messages"  class="message-box">
      <%= render 'question_box' %>
    </div>
    <form class="question-form">
      <input type="text" data-behavior="question_send" class="message-field" id="question-input" autocomplete="off">
      <button class="btn btn-primary chat-btn" data-behavior="question_send" id="send-question">Send</button>
      <br>
      <label class="anon-label"><input type="checkbox" name="checkbox" value="value" id="question-anon-box">Ask Question Anonymously</label>
    </form>
  </div>
</div>

app/views/classsessions/student_show.html.erb
<div class="row classistant-body">
  <div class="col-md-12">
    <h1 class="heading">Welcome to your Classistant Session</h1>
    <h4 class="heading">Todays topic: <%= @session.topic %></h4>
  </div>
</div>
<div class="row classistant-body">
  <div class="col-md-12 interaction-div" id="student-interaction">
    <div id="text-poll-div">
      <h3 class="heading">Your Lecturer has activated a Poll!</h3>
      <p class="heading">Do you understand the content just covered?</p>
      <p class="poll-data" id="pid"></p>
      <div class="poll-buttons">
        <button class="btn btn-success" id="text-poll-yes">Yes, I understand!</button>
        <button class="btn btn-danger" id="text-poll-no">No, I don't understand!</button>
      </div>
    </div>
    <div id="image-poll-div">
      <h3 class="heading">Your Lecturer has activated a Poll!</h3>
      <p class="heading">Do you understand the content just covered?</p>
      <p class="poll-data" id="pid"></p>
      <div class="poll-buttons">
        <form>
          <%= image_submit_tag("yes.png", :alt => "A Smiling Face Representing you Understand the content", class: "img-circle dashboard-image", id: "image-poll-yes") %>
        </form>
        <form>
          <%= image_submit_tag("no.png", :alt => "A Frowning Face Representing you don't Understand the content", class: "img-circle dashboard-image", id: "image-poll-no") %>
        </form>
      </div>
    </div>
    <div id="quiz-question-div">
      <h3 class="heading">Your Lecturer has activated a Quiz</h3>
      <p class="heading">Please fill out the following Questions and hit Submit when you're finished</p>
      <p class="heading"><strong>Note: Any questions left blank will be submitted and graded as wrong! Make sure to check your answers before submtting!</strong></p>
      <p class="quiz-data" id="qid"></p>
      <div class="col-md-12 quiz-questions">

        <form class="quiz-form">
          <div class="col-md-12 quiz-question text-center">
            <p id="quiz-question-one-text"></p>
            <br>
            <input type="text" class="quiz-field" id="question-one-field" data-behavior="quiz_send">
          </div>
          <div class="col-md-12 quiz-question text-center">
            <p id="quiz-question-two-text"></p>
            <br>
            <input type="text" class="quiz-field" id="question-two-field" data-behavior="quiz_send">
          </div>
          <div class="col-md-12 quiz-question text-center">
            <p id="quiz-question-three-text"></p>
            <br>
            <input type="text" class="quiz-field" id="question-three-field" data-behavior="quiz_send">
          </div>
          <div class="col-md-12 quiz-question text-center">
            <p id="quiz-question-four-text"></p>
            <br>
            <input type="text" class="quiz-field" id="question-four-field" data-behavior="quiz_send">
          </div>
          <div class="col-md-12 quiz-question text-center">
            <p id="quiz-question-five-text"></p>
            <br>
            <input type="text" class="quiz-field" id="question-five-field" data-behavior="quiz_send">
          </div>
          <button class="btn btn-primary quiz-submit" id="send-quiz">Submit Answers</button>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="row classistant-body session-body">
  <div class="col-md-6">
    <p class="chat-data" id="uid"><%= @user.id %></p>
    <p class="chat-data" id="utp"><%= @user_type %></p>
    <p class="chat-data" id="sid"><%= @session.id %></p>
    <h1 class="message-box-heading">Chat</h1>
    <div id="chat-messages" class="message-box">
      <%= render 'chatmessage/list'%>
    </div>
    <form class="chat-form">
      <input type="text" data-behavior="chat_send" class="message-field" id="chat-input" autocomplete="off" placeholder="Send a message..">
      <button class="btn btn-primary chat-btn" data-behavior="chat_send" id="send-chat">Send</button>
      <br>
      <label class="anon-label"><input type="checkbox" name="checkbox" value="value" id="chat-anon-box">Send Message Anonymously</label>
    </form>
  </div>
  <div class="col-md-6">
    <h1 class="message-box-heading">Ask a Question</h1>
    <div id="question-messages"  class="message-box">
      <%= render 'question_box' %>
    </div>
    <form class="question-form">
      <input type="text" data-behavior="question_send" class="message-field" id="question-input" autocomplete="off" placeholder="Answer a Question..">
      <button class="btn btn-primary chat-btn" data-behavior="question_send" id="send-question">Send</button>
      <br>
      <label class="anon-label"><input type="checkbox" name="checkbox" value="value" id="question-anon-box">Ask Question Anonymously</label>
    </form>
  </div>
</div>