config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'


  authenticate :user do
    resources :lecturers do
      get :set_admin

    end
    resources :students do
      get :send_support
      get :send_attendance
    end
    resources :dashboard
    resources :classgroups
    resources :classsessions do
      get :review
      get :end_session
    end
    resources :quiz
    resource :enrollment
    resource :joinsession

  end

  get 'static_pages/index'
  devise_for :users, controllers: { registrations: "registrations", sign_in: "login" }
  root 'static_pages#index'

end

app/models/answermessage.rb
class Answermessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :lecturer, optional: true
  belongs_to :questionmessage, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatmessage.rb
class Chatmessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :student, optional: true
  belongs_to :lecturer, optional: true

  validates :content, presence: true
end

app/models/class_group.rb
class ClassGroup < ApplicationRecord
  belongs_to :lecturer
  has_and_belongs_to_many :students
  has_many :class_sessions
end

app/models/classgroup.rb
class Classgroup < ApplicationRecord
  belongs_to :lecturer
  has_and_belongs_to_many :students
  has_many :classsessions
  has_many :quizzes

  validates :class_name, presence: true, length: {minimum: 3}
  validates :class_description, presence: true, length: {minimum: 3}
  validates :course_name, presence: true

end

app/models/classsession.rb
class Classsession < ApplicationRecord
  belongs_to :classgroup, dependent: :destroy
  has_many :chatmessages, dependent: :destroy
  has_many :questionmessages, dependent: :destroy
  has_many :answermessages, dependent: :destroy
  has_many :chatmessages
  has_and_belongs_to_many :quizzes
  has_and_belongs_to_many :students
  has_many :understanding_polls
  validates :topic, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  validates :enrollment_key, presence: true
end

app/models/joinsession.rb
class Joinsession < ApplicationRecord

end

app/models/lecturer.rb
class Lecturer < ApplicationRecord
  belongs_to :user
  has_many :classgroups
  has_many :chatmessages
  has_many :answermessages

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}

  def full_name
    return first_name + " " + last_name
  end

end

app/models/questionmessage.rb
class Questionmessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :student, optional: true
  has_one :answermessage
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :classgroup
  has_and_belongs_to_many :classsession, optional: true
  has_many :quizquestions

  validates :quiz_name, presence: true

end

app/models/quizquestion.rb
class Quizquestion < ApplicationRecord
  belongs_to :quiz
  has_many :quizquestionresponse

  validates :question_text, presence: true
  validates :question_answer, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :classgroups
  has_and_belongs_to_many :classsessions
  has_many :chatmessages
  has_many :questionmessages

  has_many :understanding_responses
  has_many :quizquestionresponses

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}


  def full_name
    return first_name + " " + last_name
  end

end

app/models/student_response.rb
class StudentResponse < ApplicationRecord
end

app/models/understanding_poll.rb
class UnderstandingPoll < ApplicationRecord
  belongs_to :classsession
  has_many :understanding_responses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :student
  has_one :lecturer

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if current_user.lecturer.nil?
      @student = current_user.student
      render 'student'
    else
      @lecturer = current_user.lecturer
      render 'lecturer'
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dashboard/lecturer.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="jumbotron">
      <h2 class="heading">Dashboard</h2>
    </div>
  </div>
</div>
<div class="row dashboard-row">
  <div class="col-md-3 col-sm-3 dashboard-option">
    <%= image_tag("class-list-icon.png", :alt => "An image of a clipboard representing your list of classes", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Classes", classgroups_url, class: "btn btn-primary dashboard-btn dashboard-class-list-btn") %>
  </div>
  <div class="col-md-3 col-sm-3  dashboard-option">
    <%= image_tag("class-session-icon.png", :alt => "A Placeholder Image", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Create a Class", new_classgroup_url, class: "btn btn-primary dashboard-btn dashboard-session-btn") %>
  </div>
  <div class="col-md-3 col-sm-3  dashboard-option">
    <%= image_tag("profile-icon.png", :alt => "An Image Representing a Profile", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Profile", lecturer_url(@lecturer), class: "btn btn-primary dashboard-btn dashboard-profile-btn") %>
  </div>
  <div class="col-md-3 col-sm-3  dashboard-option">
    <%= image_tag("settings.png", :alt => "An image of tools representing settings", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Settings", edit_user_registration_path, class: "btn btn-primary dashboard-btn dashboard-settings-btn") %>
  </div>
</div>
<% if current_user.is_admin %>
  <div class="row dashboard-row">
    <div class="col-md-3  col-sm-3 dashboard-option">
      <%= image_tag("admin.png", :alt => "A Placeholder Image", class: "img-circle dashboard-image") %>
      <br>
      <%= link_to("Add Lecturer", new_lecturer_url, class: "btn btn-primary dashboard-btn dashboard-admin-btn") %>
    </div>
    <!--<div class="col-md-3 col-sm-3  dashboard-option">-->
      <!--<%= image_tag("admin.png", :alt => "A Placeholder Image", class: "img-circle dashboard-image") %>-->
      <!--<br>-->
      <!--<%= link_to("Set Admin", new_joinsession_url, class: "btn btn-primary dashboard-btn dashboard-admin-btn") %>-->
    <!--</div>-->
  </div>
<% end %>

app/views/dashboard/student.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <h2 class="heading">Dashboard</h2>
    </div>
  </div>
</div>
<div class="row dashboard-row">
  <div class="col-md-3 dashboard-option">
    <%= image_tag("class-list-icon.png", :alt => "An image of a clipboard representing your list of classes", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Classes", classgroups_url, class: "btn btn-primary dashboard-btn dashboard-class-list-btn") %>
  </div>
  <div class="col-md-3 dashboard-option">
    <%= image_tag("class-session-icon.png", :alt => "A Placeholder Image", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Join Session", new_joinsession_url, class: "btn btn-primary dashboard-btn dashboard-session-btn") %>
  </div>
  <div class="col-md-3 dashboard-option">
    <%= image_tag("enroll-icon.png", :alt => "An image of a clipboard representing your Enrolling in a classe", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Enroll", enrollment_url, class: "btn btn-primary dashboard-btn dashboard-enroll-btn") %>
  </div>
  <div class="col-md-3 dashboard-option">
    <%= image_tag("profile-icon.png", :alt => "An Image Representing a Profile", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Profile", student_url(@student), class: "btn btn-primary dashboard-btn dashboard-profile-btn") %>
  </div>
</div>
<div class="row">
  <div class="col-md-3 dashboard-option">
    <%= image_tag("settings.png", :alt => "An image of tools representing settings", class: "img-circle dashboard-image") %>
    <br>
    <%= link_to("Settings", edit_user_registration_path, class: "btn btn-primary dashboard-btn dashboard-settings-btn") %>
  </div>
</div>