config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'


  authenticate :user do
    resources :lecturers do
      get :set_admin

    end
    resources :students do
      get :send_support
      get :send_attendance
    end
    resources :dashboard
    resources :classgroups
    resources :classsessions do
      get :review
      get :end_session
    end
    resources :quiz
    resource :enrollment
    resource :joinsession

  end

  get 'static_pages/index'
  devise_for :users, controllers: { registrations: "registrations", sign_in: "login" }
  root 'static_pages#index'

end

app/models/answermessage.rb
class Answermessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :lecturer, optional: true
  belongs_to :questionmessage, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatmessage.rb
class Chatmessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :student, optional: true
  belongs_to :lecturer, optional: true

  validates :content, presence: true
end

app/models/class_group.rb
class ClassGroup < ApplicationRecord
  belongs_to :lecturer
  has_and_belongs_to_many :students
  has_many :class_sessions
end

app/models/classgroup.rb
class Classgroup < ApplicationRecord
  belongs_to :lecturer
  has_and_belongs_to_many :students
  has_many :classsessions
  has_many :quizzes

  validates :class_name, presence: true, length: {minimum: 3}
  validates :class_description, presence: true, length: {minimum: 3}
  validates :course_name, presence: true

end

app/models/classsession.rb
class Classsession < ApplicationRecord
  belongs_to :classgroup, dependent: :destroy
  has_many :chatmessages, dependent: :destroy
  has_many :questionmessages, dependent: :destroy
  has_many :answermessages, dependent: :destroy
  has_many :chatmessages
  has_and_belongs_to_many :quizzes
  has_and_belongs_to_many :students
  has_many :understanding_polls
  validates :topic, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  validates :enrollment_key, presence: true
end

app/models/joinsession.rb
class Joinsession < ApplicationRecord

end

app/models/lecturer.rb
class Lecturer < ApplicationRecord
  belongs_to :user
  has_many :classgroups
  has_many :chatmessages
  has_many :answermessages

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}

  def full_name
    return first_name + " " + last_name
  end

end

app/models/questionmessage.rb
class Questionmessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :student, optional: true
  has_one :answermessage
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :classgroup
  has_and_belongs_to_many :classsession, optional: true
  has_many :quizquestions

  validates :quiz_name, presence: true

end

app/models/quizquestion.rb
class Quizquestion < ApplicationRecord
  belongs_to :quiz
  has_many :quizquestionresponse

  validates :question_text, presence: true
  validates :question_answer, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :classgroups
  has_and_belongs_to_many :classsessions
  has_many :chatmessages
  has_many :questionmessages

  has_many :understanding_responses
  has_many :quizquestionresponses

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}


  def full_name
    return first_name + " " + last_name
  end

end

app/models/student_response.rb
class StudentResponse < ApplicationRecord
end

app/models/understanding_poll.rb
class UnderstandingPoll < ApplicationRecord
  belongs_to :classsession
  has_many :understanding_responses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :student
  has_one :lecturer

end

app/controllers/enrollment_controller.rb
class EnrollmentController < ApplicationController

  def new
    @enrollment = Enrollment.new
  end

  def create

    #Get the enrollment key as a param from the form
    @enrollment_key = params["Enrollment Key"]

    #Create an enrollment which is only used to trigger errors on the form
    @enrollment = Enrollment.new
    @enrollment.enrollment_key = @enrollment_key

    #Find the class with the enrollment key
    @class_to_join = Classgroup.where(unique_id: @enrollment_key)
    @class_to_join = @class_to_join.to_ary.first

    #Check if the class exists or we are a student
    if !@class_to_join.nil? and current_user.student.present?

      if(@class_to_join.students.where(:user_id => current_user.id).exists?)

        p "###################"

        p "###################"

        @enrollment.errors[:enrollment_key] << ["You are already enrolled in that class"]
        render 'new'
      else

        #Get the student logged in
        @current_student = Student.find(current_user.student.id)

        #Enroll him in the class and save it
        @class_to_join.students << @current_student
        @class_to_join.save

        #Render the dashboard for now
        redirect_to '/dashboard'

      end

    else
      @enrollment.errors[:enrollment_key] << ["Invalid Enrollment Key"]
      render 'new'
    end
  end

  private
  def enrollment_params
    params.permit("Enrollment Key")
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController

  def show
    redirect_to action: 'new'
  end

  def new
    @enrollment = Enrollment.new
  end

  def create

    #Get the enrollments key as a param from the form
    @enrollment_key = params[:enrollment][:enrollment_key]

    #Create an enrollments which is only used to trigger errors on the form
    @enrollment = Enrollment.new
    @enrollment.enrollment_key = @enrollment_key

    #Find the class with the enrollments key
    @class_to_join = Classgroup.where(enrollment_key: @enrollment_key)
    @class_to_join = @class_to_join.to_ary.first

    #Check if the class exists or we are not a student
    if !@class_to_join.nil? and current_user.student.present?

      if(@class_to_join.students.where(:user_id => current_user.id).exists?)

        @enrollment.errors[:enrollment_key] << ["You are already enrolled in that class"]
        render 'new'
      else

        #Get the student logged in
        @current_student = Student.find(current_user.student.id)

        #Enroll him in the class and save it
        @class_to_join.students << @current_student
        @class_to_join.save

        #Render the dashboard for now
        redirect_to '/dashboard'

      end

    else
      @enrollment.errors[:enrollment_key] << ["Invalid Enrollment Key"]
      render 'new'
    end
  end

  private
  def enrollment_params
    params.permit("Enrollment Key")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/enrollment/enroll.html.erb
<div class="row">
  <div class="col-md-12 classistant-body">
    <div class="heading">
      <h2>Enroll in a Class</h2>
      <p>To enroll in a class simply enter the Enrollment key below and press submit</p>
    </div>
    <div class="classistant-form centered-form">
      <%= bootstrap_form_tag({controller: "enrollment", action: "create"}) do %>
        <%= number_field_tag 'Enrollment Key'%>
        <%= submit_tag("Enroll!", class: "btn btn-primary" )%>
    <% end %>
    </div>
  </div>
</div>

app/views/enrollment/new.html.erb
<div class="row">
  <div class="col-md-12 classistant-body">
    <div class="heading">
      <h2>Enroll in a Class</h2>
      <p>To enroll in a class simply enter the Enrollment key below and press submit</p>
    </div>

    <% if @enrollment.errors.any? %>
      <div class="enroll-error-explanation">
        <h2>Error Prevented you from Enrolling</h2>
        <ul>
          <% @enrollment.errors.full_messages.each do |msg| %>
            <li>
              <%= if (msg.include? "Key")
                    "Invalid Enrollment Key"
                  else
                    "You are already Enrolled in that Class"
                  end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="classistant-form centered-form">
      <%= bootstrap_form_tag({controller: "enrollment", action: "create"}) do %>
        <%= number_field_tag 'Enrollment Key' %>
        <%= submit_tag("Enroll!", class: "btn btn-primary") %>
      <% end %>
    </div>
  </div>
</div>

app/views/enrollments/enroll.html.erb
<div class="row">
  <div class="col-md-12 classistant-body">
    <div class="heading">
      <h2>Enroll in a Class</h2>
      <p>To enroll in a class simply enter the Enrollment key below and press submit</p>
    </div>
    <div class="classistant-form centered-form">
      <%= bootstrap_form_tag({controller: "enrollments", action: "create"}) do %>
        <%= number_field_tag 'Enrollment Key'%>
        <%= submit_tag("Enroll!", class: "btn btn-primary" )%>
    <% end %>
    </div>
  </div>
</div>

app/views/enrollments/new.html.erb
<div class="row">
  <div class="col-md-12 classistant-body">
    <div class="heading">
      <h2>Enroll in a Class</h2>
      <p>To enroll in a class simply enter the Enrollment key below and press submit</p>
    </div>
    <% if @enrollment.errors.any? %>
      <div class="error-explanation">
        <h2>Error Prevented you from Enrolling</h2>
        <ul>
          <% @enrollment.errors.full_messages.each do |msg| %>
            <li>
              <%= if (msg.include? "Key")
                    "Invalid Enrollment Key"
                  else
                    "You are already Enrolled in that Class"
                  end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="classistant-form centered-form">
      <%= bootstrap_form_for @enrollment, :url => enrollment_path, inline_errors: false do |f| %>
        <%= f.number_field :enrollment_key, label: 'Enrollment Key', class: 'enroll-input' %>
        <%= f.submit "Enroll", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<div class="row back-to-dashboard-btn">
  <div class="col-md-12 text-center">
    <%= link_to("Back to Dashboard", dashboard_index_url, class: "btn btn-primary not-enrolled-back-btn") %>
  </div>
</div>

app/views/enrollments/success.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <h2>Enrollment Successful!</h2>
    </div>
  </div>
</div>