config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'


  authenticate :user do
    resources :lecturers do
      get :set_admin

    end
    resources :students do
      get :send_support
      get :send_attendance
    end
    resources :dashboard
    resources :classgroups
    resources :classsessions do
      get :review
      get :end_session
    end
    resources :quiz
    resource :enrollment
    resource :joinsession

  end

  get 'static_pages/index'
  devise_for :users, controllers: { registrations: "registrations", sign_in: "login" }
  root 'static_pages#index'

end

app/models/answermessage.rb
class Answermessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :lecturer, optional: true
  belongs_to :questionmessage, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatmessage.rb
class Chatmessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :student, optional: true
  belongs_to :lecturer, optional: true

  validates :content, presence: true
end

app/models/class_group.rb
class ClassGroup < ApplicationRecord
  belongs_to :lecturer
  has_and_belongs_to_many :students
  has_many :class_sessions
end

app/models/classgroup.rb
class Classgroup < ApplicationRecord
  belongs_to :lecturer
  has_and_belongs_to_many :students
  has_many :classsessions
  has_many :quizzes

  validates :class_name, presence: true, length: {minimum: 3}
  validates :class_description, presence: true, length: {minimum: 3}
  validates :course_name, presence: true

end

app/models/classsession.rb
class Classsession < ApplicationRecord
  belongs_to :classgroup, dependent: :destroy
  has_many :chatmessages, dependent: :destroy
  has_many :questionmessages, dependent: :destroy
  has_many :answermessages, dependent: :destroy
  has_many :chatmessages
  has_and_belongs_to_many :quizzes
  has_and_belongs_to_many :students
  has_many :understanding_polls
  validates :topic, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  validates :enrollment_key, presence: true
end

app/models/joinsession.rb
class Joinsession < ApplicationRecord

end

app/models/lecturer.rb
class Lecturer < ApplicationRecord
  belongs_to :user
  has_many :classgroups
  has_many :chatmessages
  has_many :answermessages

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}

  def full_name
    return first_name + " " + last_name
  end

end

app/models/questionmessage.rb
class Questionmessage < ApplicationRecord
  belongs_to :classsession
  belongs_to :student, optional: true
  has_one :answermessage
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :classgroup
  has_and_belongs_to_many :classsession, optional: true
  has_many :quizquestions

  validates :quiz_name, presence: true

end

app/models/quizquestion.rb
class Quizquestion < ApplicationRecord
  belongs_to :quiz
  has_many :quizquestionresponse

  validates :question_text, presence: true
  validates :question_answer, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :classgroups
  has_and_belongs_to_many :classsessions
  has_many :chatmessages
  has_many :questionmessages

  has_many :understanding_responses
  has_many :quizquestionresponses

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}


  def full_name
    return first_name + " " + last_name
  end

end

app/models/student_response.rb
class StudentResponse < ApplicationRecord
end

app/models/understanding_poll.rb
class UnderstandingPoll < ApplicationRecord
  belongs_to :classsession
  has_many :understanding_responses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :student
  has_one :lecturer

end

app/controllers/classgroups_controller.rb
class ClassgroupsController < ApplicationController

  def index

    if current_user.lecturer.nil?

      if current_user.student.classgroups.nil?
        @classes = nil
      else
        @classes = current_user.student.classgroups
      end
        render 'student_view'
    else
      @classes = current_user.lecturer.classgroups
      render 'lecturer_view'
    end

  end

  def show
    @classgroup = Classgroup.find(params[:id])
    @student_count = @classgroup.students.to_ary.count

    if current_user.lecturer.nil?
      @sessions = @classgroup.classsessions
      render 'student_show'
    else
      @students = @classgroup.students
      @sessions = @classgroup.classsessions
      @quizzes = @classgroup.quizzes
      @poll_count = 0
      @quiz_count = 0;

      @classgroup.classsessions.each do |ses|
        @poll_count = @poll_count + ses.understanding_polls.count
        @quiz_count = @quiz_count + ses.quizzes.count
      end

      #Multiply by 5 because each quiz has 5 questions!
      @quiz_question_count = (@quiz_count*5)

      render 'lecturer_show'
    end


  end

  def new
    @classgroup = Classgroup.new
    @button_text = "Create Class"
  end

  def edit
    @classgroup = Classgroup.find(params[:id])
    @button_text = "Save Changes"

  end

  def create
    #Check if a Classgroup already exists, if they do, make the new ID equal to the next available ID.
    # We do this because we need to generate the Classgroup Enrollment Key based on the ID (Unique ID) of the Classgroup, which is typically
    # Only generated when the Record is saved.
    if (Classgroup.any?)
      @id = Classgroup.maximum(:id).next
    else
      @id = 0
    end

    #Manually Set all the Fields because some of the fields are set behind the scenes
    @classgroup = Classgroup.new(classgroup_params)
    @classgroup.class_name = classgroup_params[:class_name]
    @classgroup.id = @id
    @enrollment_key = generate_key(@id)
    @classgroup.enrollment_key = @enrollment_key
    @classgroup.lecturer = current_user.lecturer

    #Get the Image passed in
    @image = classgroup_params[:image_id]

    #Determine the Image based on the Param Passed from the form
    if @image == "Computer"
      @classgroup.image_id = 1
    elsif @image == "Web"
      @classgroup.image_id = 2
    elsif @image == "Business"
      @classgroup.image_id = 3
    elsif @image == "Statistics"
      @classgroup.image_id = 4
    elsif @image == "Generic"
      @classgroup.image_id = 5
    elsif @image == "Comical"
      @classgroup.image_id = 6
    else
      @classgroup.image_id = 1
    end

    if @classgroup.save
      redirect_to @classgroup
    else
      render 'new'
    end
  end

  def update

    @classgroup = Classgroup.find(params[:id])

    if @classgroup.update_attributes(classgroup_params)
      redirect_to @classgroup
    else
      format.html {render :edit}
    end
  end

  def destroy

    @classgroup = Classgroup.find(params[:id])
    @classgroup.destroy
    redirect_to classgroups_path

  end

  private
  def classgroup_params
    params.require(:classgroup).permit(:class_name, :course_name, :class_description, :classgroup, :image_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatmessage_helper.rb
module ChatmessageHelper
end

app/helpers/classgroups_helper.rb
module ClassgroupsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classgroups/_class_image.html.erb
<% if @classgroup.image_id == 1 %>
  <%= image_tag("computer-class-icon.svg", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
<% elsif @classgroup.image_id == 2 %>
  <%= image_tag("web-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
<% elsif @classgroup.image_id == 3 %>
  <%= image_tag("business-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
<% elsif @classgroup.image_id == 4 %>
  <%= image_tag("statistics-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
<% elsif @classgroup.image_id == 5 %>
  <%= image_tag("generic-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
<% elsif @classgroup.image_id == 6 %>
  <%= image_tag("comical-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
<% end %>

app/views/classgroups/_form.html.erb
<%= bootstrap_form_with(model: @classgroup, local: true) do |form| %>
  <% if @classgroup.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(@classgroup.errors.count, "error") %> prohibited this Class from being saved:</h2>

      <ul>
      <% @classgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.text_field :class_name, label: "Class Name"%>
    </div>
    <div class="field">
      <%= form.text_field :course_name, label: "Course Name"%>
    </div>
    <div class="field">
      <%= form.text_field :class_description, label: "Class Description"%>
    </div>
    <div class="field">
      <%= form.select :image_id, ['Computer', 'Web', 'Business', 'Statistics', 'Generic', 'Comical']%>
    </div>




  </div>

  <div class="actions">
    <%= form.submit @button_text, class: "btn btn-primary"%>
  </div>
<% end %>

app/views/classgroups/_student_heading.html.erb
<div class="row class-heading class-body">
  <div class="col-md-12">
    <div class="col-md-6 class-top-row">
      <div class="class-heading">
        <div class="class-details">
          <h2><%= @classgroup.class_name %> - Overview</h2>
          <p><strong>Course:</strong> <%= @classgroup.course_name %></p>
          <p><strong>Lecturer:</strong> <%= @classgroup.lecturer.full_name %></p>
          <p><strong>Enrollment Key:</strong> <%= @classgroup.enrollment_key %></p>
          <p class="class-description">"<%= @classgroup.class_description %>"</p>
        </div>
      </div>
    </div>
    <div class="col-md-6 class-top-row">
      <div class="class-heading">
        <div class="class-details">
          <div class="class-image-container">
            <%= render 'classgroups/class_image' %>
          </div>
        </div>
      </div>
    </div>
    <hr class="hr-dark">
  </div>
</div>

app/views/classgroups/edit.html.erb
<div class="row classistant-body class-form-body">

  <div class="col-md-12 standard-form">

    <div class="classistant-form">

      <h2>Edit Class</h2>
      <hr class="hr-dark">

      <%= render 'form', clasgroup: @classgroup%>

    </div>
  </div>
</div>

<% link_to 'Back', dashboard_index_url%>

app/views/classgroups/lecturer_show.html.erb
<div class="row class-heading classistant-body classgroup-body">
  <div class="col-md-12">
    <div class="col-md-6 class-top-row">
      <div class="class-heading">
        <div class="class-details">
          <h2><%= @classgroup.class_name %> - Overview</h2>
          <p><strong>Course:</strong> <%= @classgroup.course_name %></p>
          <p><strong>Lecturer:</strong> <%= @classgroup.lecturer.full_name %></p>
          <p><strong>Enrollment Key:</strong> <%= @classgroup.enrollment_key %></p>
          <p class="class-description">"<%= @classgroup.class_description %>"</p>
        </div>
      </div>
    </div>
    <div class="col-md-6 class-top-row">
      <div class="class-heading">
        <div class="class-details">
          <div class="class-image-container text-center">
            <%= render 'class_image' %>
            <%= link_to 'Edit Class', edit_classgroup_path(@classgroup), class: "btn btn-primary class-crud-button"%>
            <%= link_to 'Delete Class', @classgroup, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger class-crud-button"%>
          </div>
        </div>
      </div>
    </div>
    <hr class="hr-dark">
  </div>
</div>
<div class="row classistant-body classgroup-body">
  <div class="col-md-12">
    <h2>List of Sessions</h2>
    <%= link_to "Start new Session", {:controller => "classsessions", :action => "new", :classgroup => @classgroup }, class: "btn btn-primary start-session-btn"%>
    <%= render 'classsessions/list' %>
  </div>
</div>
<div class="row classistant-body classgroup-body">
  <div class="col-md-12">
    <h2>List of Students</h2>
    <p>Number of Students Enrolled: <%= @student_count %></p>
    <%= render 'students/list' %>
  </div>
</div>
<div class="row classistant-body classgroup-body">
  <div class="col-md-12">
    <h2>Quizzes</h2>
    <p>Below is a list of Quizzes for this class</p>
    <%= link_to "Create a Quiz", {:controller => "quiz", :action => "new", :classgroup => @classgroup }, class: "btn btn-primary create-quiz-btn"%>
    <%= render 'quiz/list' %>
  </div>
</div>

app/views/classgroups/lecturer_view.html.erb
<div class="row class-body class-list-row">
  <div class="col-md-12 class-list-view">
    <h2 class="heading">Class List</h2>
    <hr class="hr-dark">
    <%= link_to 'Create a New Class', new_classgroup_path, class: "btn btn-primary new-class-btn"%>
  </div>
</div>

<% @classes.each do |classgroup| %>
  <div class="row class-body class-list-row">
    <div class="col-md-6 class-list-view">
      <a href="/classgroups/<%=classgroup.id%>"><h4><%= classgroup.class_name %></h4></a>
      <p><%= classgroup.class_description %></p>
    </div>
    <div class="col-md-6 class-list-view">
      <%= link_to 'Edit', edit_classgroup_path(classgroup), class: "btn btn-primary"%>
      <%= link_to 'Destroy', classgroup, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"%>
      <% if classgroup.image_id == 1 %>
        <%= image_tag("computer-class-icon.svg", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 2 %>
        <%= image_tag("web-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 3 %>
        <%= image_tag("business-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 4 %>
        <%= image_tag("statistics-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 5 %>
        <%= image_tag("generic-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 6 %>
        <%= image_tag("comical-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list=image") %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/classgroups/new.html.erb
<div class="row">

  <div class="col-md-12 standard-form">

    <div class="classistant-form">

      <h2>Create a Class</h2>
      <hr>

      <%= render 'form'%>

    </div>
  </div>
</div>

<% link_to 'Back', dashboard_index_url%>

app/views/classgroups/show.html.erb
<div class="row class-heading class-body">
  <div class="col-md-12">
    <div class="col-md-6 class-top-row">
      <div class="class-heading">
        <div class="class-details">
          <h2><%= @classgroup.class_name %> - Overview</h2>
          <p><strong>Course:</strong> <%= @classgroup.course_name %></p>
          <p><strong>Lecturer:</strong> <%= @classgroup.lecturer.full_name %></p>
          <p><strong>Enrollment Key:</strong> <%= @classgroup.enrollment_key %></p>
          <p class="class-description">"<%= @classgroup.class_description %>"</p>
        </div>
      </div>
    </div>
    <div class="col-md-6 class-top-row">
      <div class="class-heading">
        <div class="class-details">
          <div class="class-image-container">
            <%= image_tag("computer-class-icon.svg", :alt => "A Picture of a Computer", class: "img-rounded class-image") %>
          </div>
        </div>
      </div>
    </div>
    <hr class="hr-dark">
  </div>
</div>
<div class="row class-body">
  <div class="col-md-6">
    <h2>List of Sessions</h2>
  </div>
  <div class="col-md-6">
    <h2>List of Students</h2>
  </div>
</div>
<div class="row class-body">
  <div class="col-md-6">
    <h2>Quizzes</h2>
  </div>
  <div class="col-md-6">
    <h2>Settings</h2>
  </div>
</div>

app/views/classgroups/student_show.html.erb
<%= render 'student_heading' %>
<div class="row class-body">
  <div class="col-md-12">
    <h2>List of Sessions</h2>
    <%= render 'classsessions/student_list' %>
  </div>
</div>

app/views/classgroups/student_view.html.erb
<% @classes.each do |classgroup| %>
  <div class="row class-body class-list-row">
    <div class="col-md-6 class-list-view">
      <a href="/classgroups/<%=classgroup.id%>"><h4><%= classgroup.class_name %></h4></a>
      <p><%= classgroup.class_description %></p>
    </div>
    <div class="col-md-6 class-list-view">
      <% if classgroup.image_id == 1 %>
        <%= image_tag("computer-class-icon.svg", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 2 %>
        <%= image_tag("web-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 3 %>
        <%= image_tag("business-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 4 %>
        <%= image_tag("statistics-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 5 %>
        <%= image_tag("generic-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list-image") %>
      <% elsif classgroup.image_id == 6 %>
        <%= image_tag("comical-class-icon.png", :alt => "A Picture of a Computer", class: "img-rounded class-list=image") %>
      <% end %>    </div>
  </div>
<% end %>

<% if !@classes.any? %>
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <h1 class="heading">Oops! Looks like you haven't enrolled in any classes yet!</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= link_to("Back to Dashboard", dashboard_index_url, class: "btn btn-primary not-enrolled-back-btn") %>
    </div>
  </div>
<% end %>